---
title: Gdclifford.Info
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: The Clifford Lab
description: Website for Clifford Lab at Emory University
url: gdclifford.info
permalink: :categories/:title
exclude:
- vendor
markdown: kramdown
host: localhost
sass:
  style: compressed
