# This updates the bibliography and is also intended to
# trigger an update to the publications page.
# 
# Source:
#   https://github.com/ad-m/github-push-action
# 
# I used ChatGPT 3.5 (November 21, 2023) for advice.
# 
# Prompts:
#  - How would I write a Github Action that once a month
#      (1) loads a secret token into an environment variable,
#      (2) calls a python script to modify some files in the
#      repository, and (3) commits and pushes the results to
#      the repository?
#  - Hm, is there a better practice for automated workflows
#      like this? It would be nice if it just sent an email to
#      the repository owner, with a button to approve or deny
#      the update.
#  - Great! If the python script has dependencies, where would
#      I put those?
# 
# Its answers didn't work, but they got me started and helped me
# search for answers that did work. The only part of its output
# I used was installing the Python requirements.

name: Update Bibliography
permissions:
  contents: write
on:
  # FIXME: update once a month using the schedule: key.
  # This makes us able to run the Action manually.
  workflow_dispatch:
jobs:
  # Job 1: download new citations to the bibliography and push them.
  download-publications:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          # these are from the "push" workflow example, and I don't know what they do,
          # but I'm not going to mess with them
          persist-credentials: false
          fetch-depth: 0
          
      - name: Set up python.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Download any new citations to the bibliography.
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: ./download_bibliography.py

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  # FIXME: perhaps ask the owner for confirmation first, before
  # automatically updating the website.
  
  # Job 2: regenerate the publications page and push it.
  make-publications-page:
    uses: ./.github/workflows/make_publications_page.yml
  
